# 성경 책 이름 영한 매핑

BOOK_NAMES = {
    # 구약 (Old Testament)
    "genesis": "창세기",
    "exodus": "출애굽기",
    "leviticus": "레위기",
    "numbers": "민수기",
    "deuteronomy": "신명기",
    "joshua": "여호수아",
    "judges": "사사기",
    "ruth": "룻기",
    "1samuel": "사무엘상",
    "2samuel": "사무엘하",
    "1kings": "열왕기상",
    "2kings": "열왕기하",
    "1chronicles": "역대상",
    "2chronicles": "역대하",
    "ezra": "에스라",
    "nehemiah": "느헤미야",
    "esther": "에스더",
    "job": "욥기",
    "psalms": "시편",
    "proverbs": "잠언",
    "ecclesiastes": "전도서",
    "song of solomon": "아가",
    "songofsolomon": "아가",
    "isaiah": "이사야",
    "jeremiah": "예레미야",
    "lamentations": "예레미야애가",
    "ezekiel": "에스겔",
    "daniel": "다니엘",
    "hosea": "호세아",
    "joel": "요엘",
    "amos": "아모스",
    "obadiah": "오바댜",
    "jonah": "요나",
    "micah": "미가",
    "nahum": "나훔",
    "habakkuk": "하박국",
    "zephaniah": "스바냐",
    "haggai": "학개",
    "zechariah": "스가랴",
    "malachi": "말라기",

    # 신약 (New Testament)
    "matthew": "마태복음",
    "mark": "마가복음",
    "luke": "누가복음",
    "john": "요한복음",
    "acts": "사도행전",
    "romans": "로마서",
    "1corinthians": "고린도전서",
    "2corinthians": "고린도후서",
    "galatians": "갈라디아서",
    "ephesians": "에베소서",
    "philippians": "빌립보서",
    "colossians": "골로새서",
    "1thessalonians": "데살로니가전서",
    "2thessalonians": "데살로니가후서",
    "1timothy": "디모데전서",
    "2timothy": "디모데후서",
    "titus": "디도서",
    "philemon": "빌레몬서",
    "hebrews": "히브리서",
    "james": "야고보서",
    "1peter": "베드로전서",
    "2peter": "베드로후서",
    "1john": "요한일서",
    "2john": "요한이서",
    "3john": "요한삼서",
    "jude": "유다서",
    "revelation": "요한계시록",
}

# 성경 순서
BOOK_ORDER = [
    # 구약
    "genesis", "exodus", "leviticus", "numbers", "deuteronomy",
    "joshua", "judges", "ruth", "1samuel", "2samuel",
    "1kings", "2kings", "1chronicles", "2chronicles", "ezra",
    "nehemiah", "esther", "job", "psalms", "proverbs",
    "ecclesiastes", "songofsolomon", "isaiah", "jeremiah", "lamentations",
    "ezekiel", "daniel", "hosea", "joel", "amos",
    "obadiah", "jonah", "micah", "nahum", "habakkuk",
    "zephaniah", "haggai", "zechariah", "malachi",
    # 신약
    "matthew", "mark", "luke", "john", "acts",
    "romans", "1corinthians", "2corinthians", "galatians", "ephesians",
    "philippians", "colossians", "1thessalonians", "2thessalonians", "1timothy",
    "2timothy", "titus", "philemon", "hebrews", "james",
    "1peter", "2peter", "1john", "2john", "3john",
    "jude", "revelation",
]


def get_korean_name(english_name: str) -> str:
    """영어 책 이름을 한글로 변환"""
    key = english_name.lower().replace(" ", "").replace("-", "")
    return BOOK_NAMES.get(key, english_name)
